# Generated by Django 3.2.6 on 2021-08-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='token',
            field=models.CharField(default='NZkmE92Z', max_length=10),
        ),
        migrations.AlterField(
            model_name='diary',
            name='tracks',
            field=models.TextField(default=''),
        ),
    ]
