# Generated by Django 3.2.6 on 2021-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210814_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='token',
            field=models.CharField(default='aQG2jMWL', max_length=10),
        ),
    ]
