# Generated by Django 3.2.6 on 2021-08-13 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_note_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='diary',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.diary'),
            preserve_default=False,
        ),
    ]
