# Generated by Django 3.2.6 on 2021-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_diary_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='token',
            field=models.CharField(default='nbODQp59', max_length=10),
        ),
        migrations.AlterField(
            model_name='diary',
            name='tracks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
