# Generated by Django 3.2.6 on 2021-08-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210814_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='token',
            field=models.CharField(default='ZoYV09ak', max_length=10),
        ),
        migrations.AlterField(
            model_name='diary',
            name='tracks',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
