# Generated by Django 3.2.6 on 2021-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_note_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='token',
            field=models.CharField(default='2w6xzQp', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='diary',
            field=models.CharField(default='', max_length=10),
        ),
    ]
