# Generated by Django 3.2.6 on 2021-08-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210814_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='tracks',
        ),
        migrations.AlterField(
            model_name='diary',
            name='token',
            field=models.CharField(default='wgDoP4j8', max_length=10),
        ),
    ]
