# Generated by Django 3.2.6 on 2021-08-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210814_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='token',
            field=models.CharField(default='AyYL88ly', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='diary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.diary'),
        ),
    ]
