# Generated by Django 3.2.6 on 2021-08-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210814_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='token',
        ),
        migrations.RemoveField(
            model_name='note',
            name='diary',
        ),
    ]
