# Generated by Django 3.2.6 on 2021-08-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_note_diary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='diary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.diary'),
        ),
    ]
